Ignore loading API key
kubernetes-sigs/boskos pull request #127
Opened 2022-06-23 10:36 UTC by Amulyam24

This PR makes the following changes:

- Does not load the API key as a part of the resource user data
- Uses the Janitor's API key for fetching the account ID

Signed-off-by: Amulyam24 <amulmek1@in.ibm.com>

2022-06-23 11:22 UTC, mkumatag requested changes
we should also consider writing UT in the future.

2022-06-23 12:36 UTC, Amulyam24 commented on internal/ibmcloud-janitor/account/account.go
> +func GetAuthenticator() (*core.IamAuthenticator, error) {
changed it for testing purposes, reverted it.

2022-06-23 15:10 UTC, mkumatag commented
/assign @chaodaiG

2022-06-27 16:49 UTC, chaodaiG commented
/approve
/hold
Please consider adding yourself as owners for the ibm and ibm-janitor folders so that you can self-approve

2022-06-28 10:29 UTC, mkumatag commented
> /approve
> /hold
> Please consider adding yourself as owners for the ibm and ibm-janitor folders so that you can self-approve

created a PR for the same: https://github.com/kubernetes-sigs/boskos/pull/129

2022-06-28 10:31 UTC, merged