Support vpc endpoints deletion in aws-janitor repo
kubernetes-sigs/boskos pull request #146
Opened 2022-08-30 16:33 UTC by youyangl

For now, the vpc endpoints(https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeVpcEndpoints) are not GCed by the aws-janitor, this change intends to support that.

TESTED=I run make, make test and make verify locally, not error found.
Tried:
go run cmd/aws-janitor/main.go --dry-run=true --all=true
go run cmd/aws-janitor/main.go --dry-run=true --all=true --enable-target-group-clean=true
locally
The log looks good to me

2022-09-02 10:02 UTC, richardcase commented
/ok-to-test

2022-09-02 20:07 UTC, stshrive requested changes

2022-09-02 20:07 UTC, stshrive commented on aws-janitor/resources/vpc_endpoints.go
> +	vpces, err := svc.DescribeVpcEndpoints(&ec2.DescribeVpcEndpointsInput{})
This has the same options passthrough issue as described above.

2022-09-06 14:26 UTC, youyangl commented on aws-janitor/resources/vpc_endpoints.go
> +	resp, err := svc.DescribeVpcEndpoints(&ec2.DescribeVpcEndpointsInput{})
No, we don't need to do so.
We describe all available vpc endpoints. When iterating over them, we use set.Mark method to record their first seen timestamps and decide which one needs to be deleted according to the timestamp and tags.
For dry run, after deciding which vpc endpoint needs to be deleted, if DryRun set to be true, we just skip the deletion step.

2022-09-06 14:59 UTC, youyangl commented on aws-janitor/resources/vpc_endpoints.go
> +	for _, vpce := range resp.VpcEndpoints {
That's a good point, thank you for reminding me that, I can use DescribeVpcEndpointsPages instead to iterate over each page.

2022-09-06 18:43 UTC, stshrive approved these changes

2022-09-06 18:45 UTC, youyangl commented
/assign chaodaiG

2022-09-06 18:52 UTC, chaodaiG commented
could you add your team as OWNERS of the aws janitor packages?

2022-09-06 18:52 UTC, chaodaiG approved these changes
/hold
Please make sure that this is backward compatible before removing hold

2022-09-14 18:49 UTC, youyangl commented
/unhold

2022-09-14 18:54 UTC, merged